# Generated by Django 3.1.7 on 2021-05-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('precioCompra', models.IntegerField(verbose_name='Precio compra')),
                ('precioVenta', models.IntegerField(verbose_name='Precio venta')),
                ('existencia', models.IntegerField(verbose_name='Existencia')),
            ],
        ),
    ]
